# Generated by Django 2.1.5 on 2019-06-26 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Framer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(default='framer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(choices=[('GIT', 'Genie Informatique et Telecommunication'), ('GEM', 'Genie ElectroMecanique '), ('GC', 'Genie Civil')], max_length=10)),
                ('classe', models.CharField(choices=[('TC2', 'Tronc Commun 2'), ('DIC1', "Diplome d'Ingenieur de Conception 1"), ('DIC2', "Diplome d'Ingenieur de Conception 2"), ('DIC3', "Diplome d'Ingenieur de Conception 3")], max_length=10)),
                ('status', models.CharField(default='student', max_length=20)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.Promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(choices=[('GIT', 'Genie Informatique et Telecommunication'), ('GEM', 'Genie ElectroMecanique '), ('GC', 'Genie Civil')], max_length=10)),
                ('responsible_dept', models.BooleanField(default=False)),
                ('responsible', models.BooleanField(default=False)),
                ('status', models.CharField(default='teacher', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
