# Generated by Django 2.2.2 on 2019-06-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190626_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GIT', 'Genie Informatique et Telecommunication'), ('GEM', 'Genie ElectroMecanique '), ('GC', 'Genie Civil')], default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
    ]
