# Generated by Django 2.2.2 on 2019-07-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190703_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('framer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to='accounts.Framer')),
                ('students', models.ManyToManyField(related_name='my_tasks', to='accounts.Student')),
            ],
        ),
    ]
