# Generated by Django 2.2.2 on 2019-07-05 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='finish_time',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='starting_time',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
    ]
