# Generated by Django 2.2.2 on 2019-07-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190705_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
