# Generated by Django 2.2.2 on 2019-07-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('starting_time', models.DateTimeField(null=True)),
                ('finish_time', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('framer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to='accounts.Framer')),
                ('students', models.ManyToManyField(related_name='my_tasks', to='accounts.Student')),
            ],
        ),
    ]
