# Generated by Django 2.2.2 on 2019-07-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='internship.Enterprise'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
    ]
