# Generated by Django 2.2.2 on 2019-07-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190705_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TC2', 'Tronc Commun 2'), ('DIC1', "Diplome d'Ingenieur de Conception 1"), ('DIC2', "Diplome d'Ingenieur de Conception 2"), ('DIC3', "Diplome d'Ingenieur de Conception 3")], default='', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='classe',
        ),
        migrations.AddField(
            model_name='student',
            name='classromm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.Classroom'),
        ),
    ]
