# Generated by Django 2.2.2 on 2019-07-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190705_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classromm',
            new_name='classroom',
        ),
    ]
