# Generated by Django 2.2.2 on 2019-07-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_student_birthday'),
        ('accounts', '0018_skill'),
    ]

    operations = [
    ]
