# Generated by Django 2.2.2 on 2019-07-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_enterprise_logo'),
        ('accounts', '0018_student_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('aim', models.CharField(default='', max_length=300)),
                ('starting_time', models.DateTimeField(null=True)),
                ('finish_time', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='internship.Enterprise')),
                ('framer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_projects', to='accounts.Framer')),
                ('students', models.ManyToManyField(to='accounts.Student')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.Project'),
        ),
    ]
