# Generated by Django 2.2.2 on 2019-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(related_name='students', to='accounts.Skill'),
        ),
    ]
