# Generated by Django 2.2.2 on 2019-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190710_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='accounts.Student'),
        ),
    ]
