# Generated by Django 2.2.2 on 2019-07-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190710_1145'),
        ('accounts', '0019_merge_20190710_1349'),
    ]

    operations = [
    ]
