# Generated by Django 2.2.2 on 2019-07-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20190710_1352'),
        ('accounts', '0019_auto_20190710_1254'),
    ]

    operations = [
    ]
