# Generated by Django 2.2.2 on 2019-07-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_merge_20190710_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='socialStatus',
            field=models.CharField(choices=[('CSE', 'Célibataire sans enfants'), ('CAE', 'Célibataire avec enfants'), ('MSE', 'Marié(e) sans enfants'), ('MAE', 'Marié(e) avec enfants')], default='', max_length=50),
        ),
    ]
