# Generated by Django 2.2.2 on 2019-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190716_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Reviewing', 'Reviewing'), ('Finish', 'Finish')], default='To Do', max_length=30),
        ),
    ]
