# Generated by Django 2.2.2 on 2019-07-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190711_2025'),
        ('accounts', '0023_auto_20190716_1232'),
    ]

    operations = [
    ]
