# Generated by Django 2.2.2 on 2019-07-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190717_1101'),
        ('accounts', '0026_merge_20190717_1253'),
    ]

    operations = [
    ]
