# Generated by Django 2.2.2 on 2019-07-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_merge_20190720_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport', models.FileField(null=True, upload_to='rapport/')),
                ('cv', models.FileField(null=True, upload_to='rapport/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.Student')),
            ],
        ),
    ]
