# Generated by Django 2.2.2 on 2019-07-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190720_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
