# Generated by Django 2.2.2 on 2019-07-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_comment_commented_at'),
        ('accounts', '0030_auto_20190720_2255'),
    ]

    operations = [
    ]
