# Generated by Django 2.2.2 on 2019-07-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_enterprise_logo'),
        ('accounts', '0032_conventionmesage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionmesage',
            name='sender_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='conventionmesage',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='internship.Convention'),
        ),
        migrations.CreateModel(
            name='ConventionChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internship.Convention')),
            ],
        ),
    ]
