# Generated by Django 2.2.2 on 2019-07-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20190722_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConventionChat',
        ),
    ]
