# Generated by Django 2.2.2 on 2019-07-23 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_delete_conventionchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='TaskComment',
        ),
        migrations.CreateModel(
            name='RapportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_rapport', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapport_comments', to='accounts.Student')),
            ],
        ),
    ]
