# Generated by Django 2.2.2 on 2019-07-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='projet',
            new_name='project',
        ),
    ]
