# Generated by Django 2.2.2 on 2019-07-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20190724_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.Framer'),
        ),
    ]
