# Generated by Django 2.2.2 on 2019-07-26 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0008_auto_20190723_1436'),
        ('accounts', '0038_auto_20190726_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConventionMesage',
            new_name='ConventionMessage',
        ),
    ]
