# Generated by Django 2.2.2 on 2019-06-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('field', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField()),
                ('leader_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
