# Generated by Django 2.2.2 on 2019-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
