# Generated by Django 2.2.2 on 2019-07-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20190705_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convention',
        ),
    ]
