# Generated by Django 2.2.2 on 2019-07-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo_enterprise'),
        ),
    ]
