# Generated by Django 2.2.2 on 2019-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_auto_20190723_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
