# Generated by Django 2.2.2 on 2019-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_auto_20190723_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
